### ISSUE TITLE
slurm_cgroup_constrain_devices is broken with 17.11

### ISSUE THREAD

**Issue by jabl** [CSCfi/ansible-role-slurm#101]
As of slurm 17.11, if slurm_cgroup_constrain_devices is set, an additional config file (default /etc/slurm/cgroup_allowed_devices_file.conf ) is needed, otherwise slurmd refuses to start.

As far as I can see, there's no need to template it, should be enough to just statically contain

<pre><code>/dev/null
/dev/urandom
/dev/zero
/dev/sda*
/dev/cpu/*/*
/dev/pts/*
/dev/ram
/dev/random
</code></pre>

Per https://groups.google.com/forum/#!topic/slurm-users/djJ_qJOmALU I'm unsure whether /dev/nvidia* needs to be there or not. Also, maybe one needs the RDMA devices as well (/dev/infiniband/*)?

**Comment by martbhell** [comment]
Fixed in #103
