### ISSUE TITLE
Ansible 2.3 warning

### ISSUE THREAD

**Issue by jabl** [CSCfi/ansible-role-slurm#83]
Ansible 2.3 is in EPEL7 now which causes the following warning to appear:

TASK [ansible-role-slurm : add cluster to accounting] *************************************************************************************************************************************************************
Thursday 27 April 2017  12:06:33 +0300 (0:00:00.758)       0:03:28.816 ******** 
 [WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: slurm_clusterlist.stdout.find("{{siteName}}") == -1
skipping: [install2]

**Comment by tiggi** [comment]
Fixed with PR #88
